-- Measure: KPI Directional Arrow
-- Purpose: Returns a Unicode arrow representing trend direction.

KPI Directional Arrow :=
VAR Current = [Total Sales]
VAR Prior =
    CALCULATE ( [Total Sales], DATEADD ( DimDate[Date], -1, MONTH ) )
VAR Diff = Current - Prior
RETURN
SWITCH (
    TRUE (),
    Diff > 0, "▲",
    Diff < 0, "▼",
    "▶"
)
