-- Measure: Current Month Total
-- Purpose: Returns total sales for the current month.

Current Month Total :=
VAR CurrentYear = YEAR ( MAX ( DimDate[Date] ) )
VAR CurrentMonth = MONTH ( MAX ( DimDate[Date] ) )
RETURN
CALCULATE (
    [Total Sales],
    FILTER (
        REMOVEFILTERS ( DimDate ),
        YEAR ( DimDate[Date] ) = CurrentYear
            && MONTH ( DimDate[Date] ) = CurrentMonth
    )
)
