-- Measure: YoY Variance
-- Purpose: Calculates year-over-year absolute variance.

YoY Variance :=
VAR CurrentYear = [Total Sales]
VAR PriorYear =
    CALCULATE (
        [Total Sales],
        SAMEPERIODLASTYEAR ( DimDate[Date] )
    )
RETURN
CurrentYear - PriorYear
