📌_Core Cohort KPI Measures
Customers = 
CALCULATE(
    DISTINCTCOUNT(DimCustomer[CustomerKey]),
    REMOVEFILTERS(DimCustomer[CustomerKey])
)


Pct Returned Within Following 3 Months = 
VAR CurrentCohort = SELECTEDVALUE(DimCustomer[First Purchase Month Start])
VAR CohortCustomers =
    FILTER(
        ALL(DimCustomer),
        DimCustomer[First Purchase Month Start] = CurrentCohort
    )
VAR Returning =
    SUMX(CohortCustomers, DimCustomer[HasReturnedNext3Months])
VAR CohortSize = COUNTROWS(CohortCustomers)
RETURN DIVIDE(Returning, CohortSize, 0)


Pct Who Returned Within 90 Days of First Purchase = 
VAR CurrentCohort = SELECTEDVALUE(DimCustomer[First Purchase Month Start])
VAR CohortCustomers =
    FILTER(
        ALL(DimCustomer),
        DimCustomer[First Purchase Month Start] = CurrentCohort
    )
VAR Returning =
    SUMX(CohortCustomers, DimCustomer[HasReturned90Days])
VAR CohortSize = COUNTROWS(CohortCustomers)
RETURN DIVIDE(Returning, CohortSize, 0)

📌_More Measures

Avg 3-Month Retention % = 
DIVIDE(
    SUMX(
        VALUES(DimCustomer[First Purchase Month Start]), 
        VAR CohortMonth = DimCustomer[First Purchase Month Start]
        VAR CohortCustomers =
            FILTER(
                ALL(DimCustomer),
                DimCustomer[First Purchase Month Start] = CohortMonth
            )
        VAR ReturningCustomers =
            SUMX(CohortCustomers, DimCustomer[HasReturnedNext3Months])
        VAR CohortSize = COUNTROWS(CohortCustomers)
        RETURN DIVIDE(ReturningCustomers, CohortSize, 0)
    ),
    COUNTROWS(VALUES(DimCustomer[First Purchase Month Start]))
)


Last Refresh Date = 
"Last Refresh: " &
FORMAT(
    MAX('LastRefresh'[LastRefresh]),
    "mmmm dd yyyy"
) &
" - " &
FORMAT(
    MAX('LastRefresh'[LastRefresh]),
    "hh:mm:ss AM/PM"
)


Retention % 90 Days = 
VAR CohortSize =
    DISTINCTCOUNT(DimCustomer[CustomerKey])
VAR Returning =
    [Returning Customers 90 Days]
RETURN
DIVIDE(Returning, CohortSize, 0)


Returning Customers 90 Days = 
VAR CurrentCohort = SELECTEDVALUE(DimCustomer[First Purchase Month Start])
VAR CohortSales =
    FILTER(
        ALL(DetailedSalesWith90DayReturn),
        DetailedSalesWith90DayReturn[Cohort Month] = FORMAT(CurrentCohort, "MMM yyyy") &&
        DetailedSalesWith90DayReturn[HasReturned90Days] = 1
    )
VAR CohortCustomers =
    DISTINCT(SELECTCOLUMNS(CohortSales, "CustomerKey", DetailedSalesWith90DayReturn[CustomerKey_Bridge]))
RETURN COUNTROWS(CohortCustomers)
 

Returning Customers Following 3 Months = 
VAR CurrentCohort = SELECTEDVALUE(DimCustomer[First Purchase Month Start])
VAR CohortSales =
    FILTER(
        ALL(DetailedSalesWith90DayReturn),
        DetailedSalesWith90DayReturn[Cohort Month] = FORMAT(CurrentCohort, "MMM yyyy") &&
        DetailedSalesWith90DayReturn[HasReturnedNext3Months] = 1
    )
VAR CohortCustomers =
    DISTINCT(SELECTCOLUMNS(CohortSales, "CustomerKey", DetailedSalesWith90DayReturn[CustomerKey_Bridge]))
RETURN COUNTROWS(CohortCustomers)


Sales % by Country = 
DIVIDE(
    [Sales by Country],
    CALCULATE([Sales by Country], ALL(FactSales[Country]))
)

Sales by Category = 
[Total Sales]

Sales by Country = 
[Total Sales]

Sales YTD = 
TOTALYTD(
    [Total Sales],
    DimDate[Date]
)

Total Profit = 
SUMX(
    FactSales,
    FactSales[Sales Amount] - FactSales[Product Standard Cost]
)

Total Sales = 
SUM('FactSales'[Sales Amount])

Tables:

Cohort90DayValidation = 
ADDCOLUMNS(
    SUMMARIZE(
        DimCustomer,
        DimCustomer[First Purchase Month Start],
        DimCustomer[Cohort Month Label]
    ),
    "Total Customers", COUNTROWS(FILTER(DimCustomer, DimCustomer[First Purchase Month Start] = EARLIER(DimCustomer[First Purchase Month Start]))),
    "Returned Within 90 Days", SUMX(FILTER(DimCustomer, DimCustomer[First Purchase Month Start] = EARLIER(DimCustomer[First Purchase Month Start])), DimCustomer[HasReturned90Days]),
    "Pct Returned 90 Days", 
        DIVIDE(
            SUMX(FILTER(DimCustomer, DimCustomer[First Purchase Month Start] = EARLIER(DimCustomer[First Purchase Month Start])), DimCustomer[HasReturned90Days]),
            COUNTROWS(FILTER(DimCustomer, DimCustomer[First Purchase Month Start] = EARLIER(DimCustomer[First Purchase Month Start]))),
            0
        )
)


DetailedReturningCustomers = 
DISTINCT(
    SELECTCOLUMNS(
        FILTER(
            // Only keep the first order per customer to avoid duplicates
            ADDCOLUMNS(
                DetailedSalesWith90DayReturn,
                "IsFirstOrder", DetailedSalesWith90DayReturn[FirstOrderFlag]
            ),
            [IsFirstOrder] = 1 &&
            NOT(ISBLANK([First Name]))
        ),
        // Columns to return
        "CustomerKey", [CustomerKey_Bridge],
        "First Name", [First Name],
        "Last Name", [Last Name],
        "Commute Distance", [Commute Distance],
        "First Purchase Date", [First Purchase Date],
        "Cohort Month", [Cohort Month],
        "Returned Within 90 Days", [HasReturned90Days],
        "Returned Within 3 Months", [HasReturnedNext3Months]
    )
)


DetailedSalesWith90DayReturn = 
ADDCOLUMNS(
    FactSales,
    
    // Bridge key for relationships
    "CustomerKey_Bridge", FactSales[CustomerKey],
    
    // Customer details
    "First Name", RELATED(FactCustomers[First Name]),
    "Last Name", RELATED(FactCustomers[Last Name]),
    "Commute Distance", RELATED(FactCustomers[Commute Distance]),
    
    // Cohort / First Purchase info
    "First Purchase Date", FORMAT(RELATED(DimCustomer[First Purchase Date]), "MMM yyyy"),
    "Cohort Month", RELATED(DimCustomer[Cohort Month Label]),
    
    // Return flags (0/1)
    "HasReturned90Days", IF(RELATED(DimCustomer[HasReturned90Days]) = 1, 1, 0),
    "HasReturnedNext3Months", IF(RELATED(DimCustomer[HasReturnedNext3Months]) = 1, 1, 0),
    // Flag first order per customer for unique counting
    "FirstOrderFlag",
        IF(
            FactSales[Order Date] = 
            CALCULATE(
                MIN(FactSales[Order Date]),
                ALLEXCEPT(FactSales, FactSales[CustomerKey])
            ),
            1,
            0
        )
)

DimCustomer = 
ADDCOLUMNS(
    SUMMARIZE(FactSales, FactSales[CustomerKey]),
    
    // 1️⃣ First Purchase Date
    "First Purchase Date",
    CALCULATE(MIN(FactSales[Order Date]), RELATEDTABLE(FactSales)),
    // 2️⃣ First Purchase Month Start
    "First Purchase Month Start",
    VAR FirstPurchase = CALCULATE(MIN(FactSales[Order Date]), RELATEDTABLE(FactSales))
    RETURN DATE(YEAR(FirstPurchase), MONTH(FirstPurchase), 1),
    // 3️⃣ Cohort Month Label
    "Cohort Month Label",
    VAR FirstPurchase = CALCULATE(MIN(FactSales[Order Date]), RELATEDTABLE(FactSales))
    RETURN FORMAT(DATE(YEAR(FirstPurchase), MONTH(FirstPurchase), 1), "MMM yyyy"),
    // 4️⃣ Has Returned Within 90 Days of First Purchase
    "HasReturned90Days",
    VAR FirstPurchase = CALCULATE(MIN(FactSales[Order Date]), RELATEDTABLE(FactSales))
    RETURN
        IF(
            CALCULATE(
                COUNTROWS(FactSales),
                FactSales[CustomerKey] = EARLIER(FactSales[CustomerKey]),
                FactSales[Order Date] > FirstPurchase,
                FactSales[Order Date] <= FirstPurchase + 90
            ) > 0, 1, 0
        ),
    // 5️⃣ Has Returned Within Following 3 Months
    "HasReturnedNext3Months",
    VAR FirstPurchase = CALCULATE(MIN(FactSales[Order Date]), RELATEDTABLE(FactSales))
    VAR StartDate = EOMONTH(FirstPurchase, 0) + 1
    VAR EndDate = EOMONTH(FirstPurchase, 3)
    RETURN
        IF(
            CALCULATE(
                COUNTROWS(FactSales),
                FactSales[CustomerKey] = EARLIER(FactSales[CustomerKey]),
                FactSales[Order Date] >= StartDate,
                FactSales[Order Date] <= EndDate
            ) > 0, 1, 0
        )
)


DimDate = 
ADDCOLUMNS(
    CALENDAR(MIN(FactSales[Order Date]), MAX(FactSales[Order Date])),
    "Year", YEAR([Date]),
    "Month Number", MONTH([Date]),
    "Month Name", FORMAT([Date], "MMMM"),
    "Month-Year", FORMAT([Date], "MMM yyyy"),
    "Month-Year Sort", YEAR([Date])*100 + MONTH([Date]),
    "Month Start", DATE(YEAR([Date]), MONTH([Date]), 1)
)

DimProductCategories = 
DISTINCT(
    SELECTCOLUMNS(
        FactProductCategories,
        "Subcategory", FactProductCategories[Subcategory],
        "Category", FactProductCategories[Category]
    )
)

DimProducts = 
ADDCOLUMNS(
    DISTINCT(
        SELECTCOLUMNS(
            FactProducts,
            "ProductKey", FactProducts[ProductKey],
            "ProductName", FactProducts[English Product Name],
            "Subcategory", FactProducts[Subcategory]
        )
    ),
    "Category",
    LOOKUPVALUE(
        FactProductCategories[Category],
        FactProductCategories[Subcategory], [Subcategory]
    )
)
