-- Measure: MoM Growth %
-- Purpose: Calculates month-over-month percentage growth.

MoM Growth % :=
VAR CurrentMonth = [Total Sales]
VAR PriorMonth =
    CALCULATE (
        [Total Sales],
        DATEADD ( DimDate[Date], -1, MONTH )
    )
RETURN
DIVIDE ( CurrentMonth - PriorMonth, PriorMonth )
