-- Measure: Current Year Total
-- Purpose: Returns total sales for the current year.

Current Year Total :=
VAR CurrentYear = YEAR ( MAX ( DimDate[Date] ) )
RETURN
CALCULATE (
    [Total Sales],
    FILTER (
        REMOVEFILTERS ( DimDate ),
        YEAR ( DimDate[Date] ) = CurrentYear
    )
)
