QoQ Growth % :=
VAR CurrentQuarter = [Total Sales]
VAR PriorQuarter =
    CALCULATE(
        [Total Sales],
        DATEADD('DimDate'[Date], -1, QUARTER)
    )
RETURN
DIVIDE(CurrentQuarter - PriorQuarter, PriorQuarter)
