-- Measure: Rolling 12 Months
-- Purpose: Calculates sales for the last 12 months from the current date.

Rolling 12 Months :=
CALCULATE (
    [Total Sales],
    DATESINPERIOD (
        DimDate[Date],
        MAX ( DimDate[Date] ),
        -12,
        MONTH
    )
)
