-- Measure: Running Total
-- Purpose: Calculates cumulative sales up to the current date.

Running Total :=
CALCULATE (
    [Total Sales],
    FILTER (
        REMOVEFILTERS ( DimDate ),
        DimDate[Date] <= MAX ( DimDate[Date] )
    )
)
