-- Measure: Same Period Last Year
-- Purpose: Returns sales for the same period in the previous year.

Same Period Last Year :=
CALCULATE (
    [Total Sales],
    SAMEPERIODLASTYEAR ( DimDate[Date] )
)
