YoY Growth % :=
VAR CurrentYear = [Total Sales]
VAR PriorYear =
    CALCULATE(
        [Total Sales],
        SAMEPERIODLASTYEAR('DimDate'[Date])
    )
RETURN
DIVIDE(CurrentYear - PriorYear, PriorYear)
